/*==============================================================*/
/* Table: CLASS_USER_INFO                                       */
/*==============================================================*/
CREATE TABLE CLASS_USER_INFO(
    USER_INFO_ID NUMBER(9),
    USER_USERNAME VARCHAR2(200),
    USER_PASSWORD VARCHAR2(200),
    USER_EMAIL VARCHAR2(200),
    constraint CR_CLASS_USER_INFO primary key (USER_INFO_ID)
)
comment on column CLASS_USER_INFO.USER_INFO_ID is
'用户ID';

comment on column CLASS_USER_INFO.USER_USERNAME is
'用户名';

comment on column CLASS_USER_INFO.USER_PASSWORD is
'用户密码';

comment on column CLASS_USER_INFO.USER_EMAIL is
'用户邮件';

SELECT * FROM CLASS_USER_INFO;

delete from CLASS_USER_INFO where user_info_id = 21;

CREATE SEQUENCE CLASS_USER_INFO_SEQ 
INCREMENT BY 1
START WITH 1;
  
  
/*==============================================================*/
/* Table: TEACH_BUILD                                       */
/*==============================================================*/
CREATE TABLE TEACH_BUILD(
   TEACH_BUILD_ID NUMBER(9),
   TEACH_BUILD_NAME VARCHAR2(200),
   constraint CR_TEACH_BUILD primary key (TEACH_BUILD_ID)
)
comment on column TEACH_BUILD.TEACH_BUILD_ID is
'教学楼ID';

comment on column TEACH_BUILD.TEACH_BUILD_NAME is
'教学楼名称';

CREATE SEQUENCE TEACH_BUILD_SEQ 
INCREMENT BY 1
START WITH 1;

SELECT * FROM TEACH_BUILD;

 SELECT * FROM TEACH_BUILD TB
        LEFT JOIN
          TEACH_BUILD_ROOM TBR
        ON
          TB.TEACH_BUILD_ID = TBR.TEACH_BUILD_ID
          
/*==============================================================*/
/* Table: TEACH_BUILD_ROOM                                       */
/*==============================================================*/
CREATE TABLE TEACH_BUILD_ROOM(
   TEACH_BUILD_ROOM_ID NUMBER(9),
   TEACH_BUILD_ROOM_NAME VARCHAR2(200),
   TEACH_BUILD_ID NUMBER(9),
   constraint CR_TEACH_BUILD_ROOM primary key (TEACH_BUILD_ROOM_ID)
)

select * from TEACH_BUILD_ROOM;

comment on column TEACH_BUILD_ROOM.TEACH_BUILD_ROOM_ID is
'教室Id';

comment on column TEACH_BUILD_ROOM.TEACH_BUILD_ROOM_NAME is
'教室名称';

comment on column TEACH_BUILD_ROOM.TEACH_BUILD_ID is
'教学楼对应id';

CREATE SEQUENCE TEACH_BUILD_ROOM_SEQ 
INCREMENT BY 1
START WITH 1;

SELECT * FROM TEACH_BUILD_ROOM;
 
ALTER TABLE TEACH_BUILD_ROOM
  ADD CONSTRAINT TEACH_BUILD_ROOM_REFERENCE
     FOREIGN KEY (TEACH_BUILD_ID) REFERENCES TEACH_BUILD (TEACH_BUILD_ID);

/*==============================================================*/
/* Table: CLASS_USER_INFO                                       */
/*==============================================================*/
SELECT * FROM TEACH_ROOM_LIGHTS;

CREATE TABLE TEACH_ROOM_LIGHTS(
   TEACH_ROOM_LIGHTS_ID NUMBER(9),
   TEACH_ROOM_LIGHTS_NAME VARCHAR2(200),
   TEACH_ROOM_LIGHTS_STATUS VARCHAR2(20),
         constraint CKC_TEACH_ROOM_LIGHTS_STATUS check (TEACH_ROOM_LIGHTS_STATUS in('0','1')),
   TEACH_BUILD_ROOM_ID NUMBER(9),
         constraint CR_TEACH_ROOM_LIGHTS primary key (TEACH_ROOM_LIGHTS_ID)
)     

comment on column TEACH_ROOM_LIGHTS.TEACH_ROOM_LIGHTS_ID is
'电源编号ID';

comment on column TEACH_ROOM_LIGHTS.TEACH_ROOM_LIGHTS_NAME is
'电源操作名称';

comment on column TEACH_ROOM_LIGHTS.TEACH_ROOM_LIGHTS_STATUS is
'电源状态0:关闭 1:开启状态';

comment on column TEACH_ROOM_LIGHTS.TEACH_BUILD_ROOM_ID is
'教室ID';

CREATE SEQUENCE TEACH_ROOM_LIGHTS_SEQ 
INCREMENT BY 1
START WITH 1;

SELECT *FROM TEACH_ROOM_LIGHTS;

ALTER TABLE TEACH_ROOM_LIGHTS
  ADD CONSTRAINT TEACH_ROOM_LIGHTS_REFERENCE
     FOREIGN KEY (TEACH_BUILD_ROOM_ID) REFERENCES TEACH_BUILD_ROOM (TEACH_BUILD_ROOM_ID);

     
---------------------------------------------------------------------------------------------------------------------------
--data
INSERT INTO CLASS_USER_INFO
  (USER_INFO_ID, USER_USERNAME, USER_PASSWORD, USER_EMAIL)
VALUEs
  (CLASS_USER_INFO_SEQ.NEXTVAL, 'a', 'a', 'acs@qq.com');
  
INSERT INTO TEACH_BUILD
  (TEACH_BUILD_ID, TEACH_BUILD_NAME)
VALUES
  (TEACH_BUILD_SEQ.NEXTVAL, '一号教学楼');
INSERT INTO TEACH_BUILD
  (TEACH_BUILD_ID, TEACH_BUILD_NAME)
VALUES
  (TEACH_BUILD_SEQ.NEXTVAL, '二号教学楼');
  INSERT INTO TEACH_BUILD
  (TEACH_BUILD_ID, TEACH_BUILD_NAME)
VALUES
  (TEACH_BUILD_SEQ.NEXTVAL, '三号教学楼');
  INSERT INTO TEACH_BUILD
  (TEACH_BUILD_ID, TEACH_BUILD_NAME)
VALUES
  (TEACH_BUILD_SEQ.NEXTVAL, '四号教学楼');
           
INSERT INTO TEACH_BUILD_ROOM
  (TEACH_BUILD_ROOM_ID, TEACH_BUILD_ROOM_NAME, TEACH_BUILD_ID)
VALUES
  (TEACH_BUILD_ROOM_SEQ.NEXTVAL, '4501', 4);
INSERT INTO TEACH_BUILD_ROOM
  (TEACH_BUILD_ROOM_ID, TEACH_BUILD_ROOM_NAME, TEACH_BUILD_ID)
VALUES
  (TEACH_BUILD_ROOM_SEQ.NEXTVAL, '4502', 4);
INSERT INTO TEACH_BUILD_ROOM
  (TEACH_BUILD_ROOM_ID, TEACH_BUILD_ROOM_NAME, TEACH_BUILD_ID)
VALUES
  (TEACH_BUILD_ROOM_SEQ.NEXTVAL, '4503', 4);
INSERT INTO TEACH_BUILD_ROOM
  (TEACH_BUILD_ROOM_ID, TEACH_BUILD_ROOM_NAME, TEACH_BUILD_ID)
VALUES
  (TEACH_BUILD_ROOM_SEQ.NEXTVAL, '4504', 4);
INSERT INTO TEACH_BUILD_ROOM
  (TEACH_BUILD_ROOM_ID, TEACH_BUILD_ROOM_NAME, TEACH_BUILD_ID)
VALUES
  (TEACH_BUILD_ROOM_SEQ.NEXTVAL, '4505', 4);
 
INSERT INTO TEACH_ROOM_LIGHTS
  (TEACH_ROOM_LIGHTS_ID,
   TEACH_ROOM_LIGHTS_NAME,
   TEACH_ROOM_LIGHTS_STATUS,
   TEACH_BUILD_ROOM_ID)
VALUES
  (TEACH_ROOM_LIGHTS_SEQ.NEXTVAL, '前左一', '0',20);
INSERT INTO TEACH_ROOM_LIGHTS
  (TEACH_ROOM_LIGHTS_ID,
   TEACH_ROOM_LIGHTS_NAME,
   TEACH_ROOM_LIGHTS_STATUS,
   TEACH_BUILD_ROOM_ID)
VALUES
  (TEACH_ROOM_LIGHTS_SEQ.NEXTVAL, '前右一', '0',20);
INSERT INTO TEACH_ROOM_LIGHTS
  (TEACH_ROOM_LIGHTS_ID,
   TEACH_ROOM_LIGHTS_NAME,
   TEACH_ROOM_LIGHTS_STATUS,
   TEACH_BUILD_ROOM_ID)
VALUES
  (TEACH_ROOM_LIGHTS_SEQ.NEXTVAL, '后右二', '0',20);
INSERT INTO TEACH_ROOM_LIGHTS
  (TEACH_ROOM_LIGHTS_ID,
   TEACH_ROOM_LIGHTS_NAME,
   TEACH_ROOM_LIGHTS_STATUS,
   TEACH_BUILD_ROOM_ID)
VALUES
  (TEACH_ROOM_LIGHTS_SEQ.NEXTVAL, '后左二', '0',20);
           
           
